services:
  app:
    build: .
    container_name: library-for-one
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: library
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: library-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
